version: "2"

volumes:
  data:

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    expose:
      - 5001
    ports:
      - 5001:5001

    restart: unless-stopped
    volumes:
      - data:/main/data